### ISSUE TITLE
Make Client Load Config For Distribution

### ISSUE THREAD

**Issue by CoreyShupe** [CoreyShupe/Synthesis#4]
This is a micro-optimization, but it might be nice if we loaded the config into the `SynthesisClient` class and distributed it via the context passed through events and commands for Harmony.

More of a nit, but loading it in most of our files seems like a lot more overhead than necessary.

**Comment by DebitCardz** [comment]
Being worked on in #6.

**Comment by CoreyShupe** [comment]
Fixed in #6
